# For all keys indicated, please set env vars and update this config accordingly. 
# Do NOT add your actual keys to this config.

# Private key used for signing all data sent to the relayer.
private_key = "PRIVATE_KEY"

# Exchange keys
cryptocompare_key = "CRYPTOCOMPARE_KEY"
numerofx_key = "NUMEROFX_KEY"
# ...add more

# TODO: should any of this be hard coded?
collateral_pairs = ["USDC/NGN", "USDC/JPY", "ETH/NGN", "ETH/JPY"]
interval = 20000
relayer_address = "localhost:8080"
