collateral_pair = ["abc/def", "ghi/jkl"]
exchange_orign = ""
exchange_key = ""
interval = 5000
ethereum_key = ""
topic = "ozi_test"
bootstrap_nodes = [
    # replace with list of our servers IP address / TCP port and generated peer id
    "/ip4/127.0.0.1/tcp/61923/p2p/12D3KooWDkgfBMii8QZFMqpiZWUmRjiPSMo8P2MJEyVsoYCLLZ58",
]
